 
version: '2'
services:
  angular:
    build: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/:/var/www/app
  express:
    build: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/:/var/www/app
    links:
      - database
    environment:
      - MONGO_URI=mongodb://database/ParaDemic
  ml:
    build: Machine_Learning
    ports:
      - "8000:8000"
    volumes:
      - ./Machine_Learning/:/var/www/app
    links:
      - database
      - express
      
  database:
    image: mongo
    ports:
      - "27018:27018"
    volumes:
      - ./data-prod:/data/db
